version: 2.1
orbs:
  codecov: codecov/codecov@3

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: cimg/ruby:3.1.2-node
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
          PGPORT: 5432
          DATABASE_URL: postgresql://myapp@localhost:5432/car_advertisements_web_test
      - image: circleci/postgres:11.3-alpine
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: car_advertisements_web_test

caches:
  - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run:
          name: install required gems
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle
      - run:
          name: Set up DB
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:migrate


  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $TEST_FILES
            curl -s https://codecov.io/bash | bash -s -- -t 478c35d8-0844-42ac-b478-d1fea7a21a58 -f /tmp/test-results/coverage/.resultset.json
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage
      - codecov/upload

  run_rubocop:
    steps:
      - run:
          name: run rubocop
          command: bundle exec rubocop

  run_fasterer:
    steps:
      - run:
          name: run fasterer
          command: bundle exec fasterer

  run_bundle_audit:
    steps:
      - run:
          name: run bundle audit
          command: bundle exec bundler-audit check --update

  run_rails_best_practices:
    steps:
      - run:
          name: run rails_best_practices
          command: bundle exec rails_best_practices .
jobs:
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_rubocop
      - run_fasterer
      - run_bundle_audit
      - run_rails_best_practices

  specs:
    executor: default
    parallelism: 2
    steps:
      - setup_environment
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - specs:
          requires:
            - lintering
