version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: cimg/ruby:3.1.2-node

caches:
  - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run:
          name: install required gems
          command: bundle install
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle

  run_specs:
    steps:
#      - defaults
      - run:
          name: run specs
          command: bundle exec rspec

  run_rubocop:
    steps:
#      - defaults
      - run:
          name: run rubocop
          command: bundle exec rubocop

  run_fasterer:
    steps:
#      - defaults
      - run:
          name: run fasterer
          command: bundle exec fasterer

jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_rubocop
      - run_fasterer

#  specs:
#    executor: default
#    steps:
#      - defaults
#      - run_specs

workflows:
  build:
    jobs:
      - lintering
#      - specs:
#          requires:
#            - lintering
