name: Codecov

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '3.1.2' ]

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Create and migrate database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run RSpec tests
        run: bundle exec rspec
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/.resultset.json
          flags: rspec
